### PR TITLE
Remove unused code

### LINKED ISSUE #1575: unused (unused functions, variables, fields, constants, ...) - 152 findings
Findings:

```
builtin/credential/cert/path_crls.go:180:6: func parseSerialString is unused (unused)
func parseSerialString(input string) (*big.Int, error) {
builtin/credential/cert/path_login.go:665:19: func (*backend).checkForValidChain is unused (unused)
func (b *backend) checkForValidChain(chains [][]*x509.Certificate) bool {
builtin/credential/cert/path_login_test.go:359:6: func serialFromBigInt is unused (unused)
func serialFromBigInt(serial *big.Int) string {
builtin/credential/cert/test_responder.go:33:2: var tryLaterErrorResponse is unused (unused)
	tryLaterErrorResponse         = []byte{0x30, 0x03, 0x0A, 0x01, 0x03}
builtin/credential/cert/test_responder.go:34:2: var sigRequredErrorResponse is unused (unused)
	sigRequredErrorResponse       = []byte{0x30, 0x03, 0x0A, 0x01, 0x05}
builtin/credential/cert/test_responder.go:113:5: var hashToString is unused (unused)
var hashToString = map[crypto.Hash]string{
builtin/credential/jwt/path_cel_login.go:214:26: func (*jwtAuthBackend).pathCelLoginRenew is unused (unused)
func (b *jwtAuthBackend) pathCelLoginRenew(ctx context.Context, req *logical.Request, data *framework.FieldData) (*logical.Response, error) {
builtin/credential/jwt/path_cel_login.go:243:6: func marshalCIDRs is unused (unused)
func marshalCIDRs(cidrs []string) []*sockaddr.SockAddrMarshaler {
builtin/credential/jwt/path_ui.go:15:6: func pathUI is unused (unused)
func pathUI(b *jwtAuthBackend) *framework.Path {
builtin/credential/jwt/path_ui.go:32:26: func (*jwtAuthBackend).pathUI is unused (unused)
func (b *jwtAuthBackend) pathUI(ctx context.Context, req *logical.Request, d *framework.FieldData) (*logical.Response, error) {
builtin/credential/token/cli.go:20:2: field testStdin is unused (unused)
	testStdin  io.Reader
builtin/logical/database/mockv5.go:19:2: field config is unused (unused)
	config map[string]interface{}
builtin/logical/database/rotation_test.go:856:6: type createUserCommand is unused (unused)
type createUserCommand struct {
builtin/logical/database/version_wrapper_test.go:366:3: field expectedResp is unused (unused)
		expectedResp v5.UpdateUserResponse
builtin/logical/kv/path_metadata.go:817:2: const metadataHelpSyn is unused (unused)
	metadataHelpSyn  = `Allows interaction with key metadata and settings in the KV store.`
builtin/logical/kv/path_metadata.go:818:2: const metadataHelpDesc is unused (unused)
	metadataHelpDesc = `
builtin/logical/pki/crl_util.go:40:6: type revocationRequest is unused (unused)
type revocationRequest struct {
builtin/logical/pki/crl_util.go:44:6: type revocationConfirmed is unused (unused)
type revocationConfirmed struct {
builtin/logical/pki/crl_util.go:452:23: func (*crlBuilder).rebuildDeltaCRLs is unused (unused)
func (cb *crlBuilder) rebuildDeltaCRLs(sc *storageContext, forceNew bool) ([]string, error) {
builtin/logical/pki/crl_util.go:509:6: func tryRevokeCertBySerial is unused (unused)
func tryRevokeCertBySerial(sc *storageContext, config *crlConfig, serial string) (*logical.Response, error) {
builtin/logical/pki/storage.go:1435:27: func (*storageContext).listRevokedCerts is unused (unused)
func (sc *storageContext) listRevokedCerts() ([]string, error) {
builtin/logical/pki/test_helpers.go:97:6: func requireMatchingPublicKeys is unused (unused)
func requireMatchingPublicKeys(t *testing.T, cert *x509.Certificate, key crypto.PublicKey) {
builtin/logical/pki/test_helpers.go:291:6: func requireSuccessNilResponse is unused (unused)
func requireSuccessNilResponse(t *testing.T, resp *logical.Response, err error, msgAndArgs ...interface{}) {
builtin/logical/pki/test_helpers.go:397:6: func summarizeCrl is unused (unused)
func summarizeCrl(t *testing.T, crl *x509.RevocationList) string {
builtin/logical/pki/test_helpers.go:427:6: func performOcspPost is unused (unused)
func performOcspPost(t *testing.T, cert *x509.Certificate, issuerCert *x509.Certificate, client *api.Client, ocspPath string) *ocsp.Response {
builtin/logical/pki/util.go:57:6: func serialToBigInt is unused (unused)
func serialToBigInt(serial string) (*big.Int, bool) {
builtin/logical/pki/util.go:291:6: func sliceToMapKey is unused (unused)
func sliceToMapKey(s []string) map[string]struct{} {
builtin/logical/pkiext/test_helpers.go:21:6: func requireFieldsSetInResp is unused (unused)
func requireFieldsSetInResp(t *testing.T, resp *logical.Response, fields ...string) {
builtin/logical/pkiext/test_helpers.go:42:6: func requireSuccessNilResponse is unused (unused)
func requireSuccessNilResponse(t *testing.T, resp *logical.Response, err error, msgAndArgs ...interface{}) {
builtin/logical/ssh/backend_test.go:42:2: const testKeyName is unused (unused)
	testKeyName = "testKeyName"
builtin/logical/ssh/backend_test.go:2728:6: func submitCAIssuerStep is unused (unused)
func submitCAIssuerStep(issuerName string, parameters map[string]interface{}) logicaltest.TestStep {
builtin/logical/ssh/backend_test.go:2740:6: func updateIssuersConfigStep is unused (unused)
func updateIssuersConfigStep(parameters map[string]interface{}) logicaltest.TestStep {
builtin/logical/ssh/storage.go:375:27: func (*storageContext).isIssuersEmpty is unused (unused)
func (sc *storageContext) isIssuersEmpty() (bool, error) {
builtin/logical/ssh/util.go:38:6: func generateRSAKeys is unused (unused)
func generateRSAKeys(keyBits int) (publicKeyRsa string, privateKeyRsa string, err error) {
command/agent/exec/test-app/main.go:29:2: var ignoreStopSignal is unused (unused)
	ignoreStopSignal     bool
command/agent/testing.go:23:7: const envVarRunAccTests is unused (unused)
const envVarRunAccTests = "BAO_ACC"
command/agent/testing.go:25:5: var runAcceptanceTests is unused (unused)
var runAcceptanceTests = api.ReadBaoVariable(envVarRunAccTests) == "1"
command/agent_test.go:1420:2: field failCount is unused (unused)
	failCount            int
command/agentproxyshared/cache/api_proxy.go:21:2: field l is unused (unused)
	l                       sync.RWMutex
command/agentproxyshared/cache/api_proxy.go:22:2: field lastIndexStates is unused (unused)
	lastIndexStates         []string
command/base_flags.go:652:6: func appendDurationSuffix is unused (unused)
func appendDurationSuffix(s string) string {
command/command_test.go:339:6: func testClient is unused (unused)
func testClient(tb testing.TB, addr string, token string) *api.Client {
command/operator_diagnose.go:55:2: field reloadFuncsLock is unused (unused)
	reloadFuncsLock      *sync.RWMutex
command/operator_diagnose.go:56:2: field reloadFuncs is unused (unused)
	reloadFuncs          *map[string][]reloadutil.ReloadFunc
command/operator_diagnose.go:58:2: field startedCh is unused (unused)
	startedCh            chan struct{} // for tests
command/operator_diagnose.go:59:2: field reloadedCh is unused (unused)
	reloadedCh           chan struct{} // for tests
command/operator_diagnose.go:136:2: const status_unknown is unused (unused)
	status_unknown = "[      ] "
command/operator_diagnose.go:137:2: const status_ok is unused (unused)
	status_ok      = "\u001b[32m[  ok  ]\u001b[0m "
command/operator_diagnose.go:138:2: const status_failed is unused (unused)
	status_failed  = "\u001b[31m[failed]\u001b[0m "
command/operator_diagnose.go:139:2: const status_warn is unused (unused)
	status_warn    = "\u001b[33m[ warn ]\u001b[0m "
command/operator_diagnose.go:140:2: const same_line is unused (unused)
	same_line      = "\u001b[F"
command/pgp_test.go:97:6: func parseDecryptAndTestUnsealKeys is unused (unused)
func parseDecryptAndTestUnsealKeys(t *testing.T,
command/pki_health_check_test.go:310:6: func testPKIHealthCheckCommand is unused (unused)
func testPKIHealthCheckCommand(tb testing.TB) (*cli.MockUi, *PKIHealthCheckCommand) {
command/pki_issue_intermediate.go:22:2: field flagConfig is unused (unused)
	flagConfig          string
command/pki_issue_intermediate.go:23:2: field flagReturnIndicator is unused (unused)
	flagReturnIndicator string
command/pki_issue_intermediate.go:24:2: field flagDefaultDisabled is unused (unused)
	flagDefaultDisabled bool
command/pki_issue_intermediate.go:25:2: field flagList is unused (unused)
	flagList            bool
command/pki_list_intermediate.go:21:2: field flagConfig is unused (unused)
	flagConfig          string
command/pki_list_intermediate.go:22:2: field flagReturnIndicator is unused (unused)
	flagReturnIndicator string
command/pki_list_intermediate.go:23:2: field flagDefaultDisabled is unused (unused)
	flagDefaultDisabled bool
command/pki_list_intermediate.go:24:2: field flagList is unused (unused)
	flagList            bool
command/pki_reissue_intermediate.go:27:2: field flagConfig is unused (unused)
	flagConfig          string
command/pki_reissue_intermediate.go:28:2: field flagReturnIndicator is unused (unused)
	flagReturnIndicator string
command/pki_reissue_intermediate.go:29:2: field flagDefaultDisabled is unused (unused)
	flagDefaultDisabled bool
command/pki_reissue_intermediate.go:30:2: field flagList is unused (unused)
	flagList            bool
command/plugin_reload_test.go:26:6: func testPluginReloadStatusCommand is unused (unused)
func testPluginReloadStatusCommand(tb testing.TB) (*cli.MockUi, *PluginReloadStatusCommand) {
command/server/config.go:117:2: const sectionSeal is unused (unused)
	sectionSeal = "Seal"
command/server/config_test_helpers.go:1174:6: func testConfigRaftAutopilot is unused (unused)
func testConfigRaftAutopilot(t *testing.T) {
helper/builtinplugins/registry.go:61:6: type removedBackend is unused (unused)
type removedBackend struct {
helper/builtinplugins/registry.go:65:6: func removedFactory is unused (unused)
func removedFactory(ctx context.Context, config *logical.BackendConfig) (logical.Backend, error) {
helper/storagepacker/storagepacker.go:25:2: const bucketCount is unused (unused)
	bucketCount = 256
helper/testhelpers/logical/testing_test.go:79:17: func (*mockT).failed is unused (unused)
func (t *mockT) failed() bool {
helper/testhelpers/logical/testing_test.go:83:17: func (*mockT).failMessage is unused (unused)
func (t *mockT) failMessage() string {
http/handler.go:573:6: func stripPrefix is unused (unused)
func stripPrefix(prefix, path string) (string, bool) {
internalshared/configutil/encrypt_decrypt_test.go:16:6: func getAEADTestKMS is unused (unused)
func getAEADTestKMS(t *testing.T) {
internalshared/configutil/listener_test.go:14:7: type args is unused (unused)
	type args struct {
physical/crosstest/cross_test.go:102:6: func replayOps is unused (unused)
func replayOps(t *testing.T, file string) []*inmem.InmemOp {
physical/raft/raft_test.go:32:6: func connectPeers is unused (unused)
func connectPeers(nodes ...*RaftBackend) {
physical/raft/raft_test.go:45:6: func stepDownLeader is unused (unused)
func stepDownLeader(t *testing.T, node *RaftBackend) {
physical/raft/raft_test.go:63:6: func waitForLeader is unused (unused)
func waitForLeader(t *testing.T, nodes ...*RaftBackend) *RaftBackend {
physical/raft/snapshot_test.go:28:6: type idAddr is unused (unused)
type idAddr struct {
physical/raft/snapshot_test.go:32:18: func (*idAddr).Network is unused (unused)
func (a *idAddr) Network() string { return "inmem" }
physical/raft/snapshot_test.go:33:18: func (*idAddr).String is unused (unused)
func (a *idAddr) String() string  { return a.id }
physical/raft/streamlayer.go:167:2: field dialerFunc is unused (unused)
	dialerFunc func(string, time.Duration) (net.Conn, error)
physical/raft/varint.go:41:2: var errSmallBuffer is unused (unused)
	errSmallBuffer = errors.New("Buffer Too Small")
physical/raft/varint.go:42:2: var errLargeValue is unused (unused)
	errLargeValue  = errors.New("Value is Larger than 64 bits")
serviceregistration/kubernetes/testing/testserver.go:50:2: var pathToFiles is unused (unused)
	pathToFiles = func() string {
serviceregistration/kubernetes/testing/testserver.go:234:6: func readFile is unused (unused)
func readFile(fileName string) (string, error) {
vault/acl.go:41:2: field rgpPolicies is unused (unused)
	rgpPolicies []*Policy
vault/auth.go:472:16: func (*Core).remountCredEntryForceInternal is unused (unused)
func (c *Core) remountCredEntryForceInternal(ctx context.Context, path string, updateStorage bool) error {
vault/cluster.go:288:16: func (*Core).loadCluster is unused (unused)
func (c *Core) loadCluster(ctx context.Context) error {
vault/core.go:94:2: const groupPolicyApplicationModeAny is unused (unused)
	groupPolicyApplicationModeAny = "any"
vault/core.go:3076:16: func (*Core).readFeatureFlags is unused (unused)
func (c *Core) readFeatureFlags(ctx context.Context) (*FeatureFlags, error) {
vault/core_util_common.go:24:16: func (*Core).loadHeaderHMACKey is unused (unused)
func (c *Core) loadHeaderHMACKey(ctx context.Context) error {
vault/counters.go:11:2: const requestCounterDatePathFormat is unused (unused)
	requestCounterDatePathFormat = "2006/01"
vault/counters_test.go:17:6: func testParseTime is unused (unused)
func testParseTime(t *testing.T, format, timeval string) time.Time {
vault/diagnose/output.go:37:5: var errUnimplemented is unused (unused)
var errUnimplemented = errors.New("unimplemented")
vault/diagnose/output.go:99:2: field rootSpan is unused (unused)
	rootSpan   sdktrace.ReadOnlySpan
vault/dynamic_system_view.go:23:6: type ctxKeyForwardedRequestMountAccessor is unused (unused)
type ctxKeyForwardedRequestMountAccessor struct{}
vault/dynamic_system_view.go:25:46: func ctxKeyForwardedRequestMountAccessor.String is unused (unused)
func (c ctxKeyForwardedRequestMountAccessor) String() string {
vault/expiration.go:501:29: func (*ExpirationManager).invalidate is unused (unused)
func (m *ExpirationManager) invalidate(key string) {
vault/expiration_test.go:34:5: var testImagePull is unused (unused)
var testImagePull sync.Once
vault/expiration_test.go:53:6: func mockBackendExpiration is unused (unused)
func mockBackendExpiration(t testing.TB, backend physical.Backend) (*Core, *ExpirationManager) {
vault/external_tests/quotas/quotas_test.go:24:2: const testLookupOnlyPolicy is unused (unused)
	testLookupOnlyPolicy = `
vault/external_tests/quotas/quotas_test.go:124:6: func waitForRemovalOrTimeout is unused (unused)
func waitForRemovalOrTimeout(c *api.Client, path string, tick, to time.Duration) error {
vault/external_tests/storage/crosstest/cross_test.go:78:6: func replayOps is unused (unused)
func replayOps(t *testing.T, file string) []*inmem.InmemOp {
vault/identity_store_structs.go:24:2: const entityPrefix is unused (unused)
	entityPrefix = "entity/"
vault/identity_store_test.go:655:6: func testCoreWithIdentityTokenAppRoleRoot is unused (unused)
func testCoreWithIdentityTokenAppRoleRoot(ctx context.Context, t *testing.T) (*Core, *IdentityStore, *TokenStore, string, string) {
vault/keyring.go:28:2: var disabledRotationConfig is unused (unused)
	disabledRotationConfig = KeyRotationConfig{
vault/logical_passthrough.go:116:30: func (*PassthroughBackend).handleRevoke is unused (unused)
func (b *PassthroughBackend) handleRevoke(ctx context.Context, req *logical.Request, data *framework.FieldData) (*logical.Response, error) {
vault/logical_system.go:3364:25: func (*SystemBackend).handleWrappingPubkey is unused (unused)
func (b *SystemBackend) handleWrappingPubkey(ctx context.Context, req *logical.Request, data *framework.FieldData) (*logical.Response, error) {
vault/login_mfa.go:1811:6: func formatUsername is unused (unused)
func formatUsername(format string, alias *identity.Alias, entity *identity.Entity) string {
vault/login_mfa.go:2950:5: var mfaHelp is unused (unused)
var mfaHelp = map[string][2]string{
vault/mount.go:1056:16: func (*Core).remountForceInternal is unused (unused)
func (c *Core) remountForceInternal(ctx context.Context, path string, updateStorage bool) error {
vault/mount_util_shared.go:10:16: func (*Core).addBackendWriteForwardedPaths is unused (unused)
func (c *Core) addBackendWriteForwardedPaths(backend logical.Backend, viewPath string) {
vault/mount_util_shared.go:19:6: func collectBackendSpecialPaths is unused (unused)
func collectBackendSpecialPaths(backend logical.Backend, viewPath string, accessor func(specialPaths *logical.Paths) []string) []string {
vault/namespace_store.go:266:27: func (*NamespaceStore).invalidate is unused (unused)
func (ns *NamespaceStore) invalidate(ctx context.Context, path string) error {
vault/policy_store.go:240:24: func (*PolicyStore).invalidate is unused (unused)
func (ps *PolicyStore) invalidate(ctx context.Context, name string, policyType PolicyType) {
vault/policy_test.go:132:5: var rawPolicyJSON is unused (unused)
var rawPolicyJSON = strings.TrimSpace(`
vault/quotas/quotas.go:76:6: type leaseWalkFunc is unused (unused)
type leaseWalkFunc func(context.Context, func(request *Request) bool) error
vault/seal.go:46:2: const hsmStoredIVPath is unused (unused)
	hsmStoredIVPath = "core/hsm/iv"
vault/testing.go:69:2: const testSharedPublicKey is unused (unused)
	testSharedPublicKey = `
vault/testing.go:72:2: const testSharedPrivateKey is unused (unused)
	testSharedPrivateKey = `
vault/token_store.go:771:2: field identityPoliciesDeriverFunc is unused (unused)
	identityPoliciesDeriverFunc func(string) (*identity.Entity, []string, error)
vault/wrapping_util.go:12:6: func forwardWrapRequest is unused (unused)
func forwardWrapRequest(context.Context, *Core, *logical.Request, *logical.Response, *logical.Auth) (*logical.Response, error) {
sdk/database/dbplugin/databasemiddleware.go:264:2: field l is unused (unused)
	l         sync.RWMutex
sdk/database/dbplugin/v5/grpc_client_test.go:539:2: field closeErr is unused (unused)
	closeErr error
sdk/framework/openapi_test.go:895:6: func getPathOp is unused (unused)
func getPathOp(pi *OASPathItem, op string) *OASOperation {
sdk/helper/keysutil/lock_manager.go:27:5: var errNeedExclusiveLock is unused (unused)
var errNeedExclusiveLock = errors.New("an exclusive lock is needed for this operation")
sdk/helper/keysutil/policy.go:266:6: type deprecatedKeyEntryMap is unused (unused)
type deprecatedKeyEntryMap map[int]KeyEntry
sdk/helper/keysutil/policy.go:269:34: func deprecatedKeyEntryMap.MarshalJSON is unused (unused)
func (kem deprecatedKeyEntryMap) MarshalJSON() ([]byte, error) {
sdk/helper/keysutil/policy.go:278:34: func deprecatedKeyEntryMap.UnmarshalJSON is unused (unused)
func (kem deprecatedKeyEntryMap) UnmarshalJSON(data []byte) error {
sdk/helper/keysutil/policy_test.go:284:6: func testArchivingCommon is unused (unused)
func testArchivingCommon(t *testing.T, lm *LockManager) {
sdk/helper/ocsp/client.go:54:2: const ocspFailOpenNotSet is unused (unused)
	ocspFailOpenNotSet FailOpenMode = iota
sdk/helper/ocsp/client.go:62:2: const ocspModeFailOpen is unused (unused)
	ocspModeFailOpen   = "FAIL_OPEN"
sdk/helper/ocsp/client.go:63:2: const ocspModeFailClosed is unused (unused)
	ocspModeFailClosed = "FAIL_CLOSED"
sdk/helper/ocsp/client.go:64:2: const ocspModeInsecure is unused (unused)
	ocspModeInsecure   = "INSECURE"
sdk/helper/ocsp/client.go:67:7: const ocspCacheKey is unused (unused)
const ocspCacheKey = "ocsp_cache"
sdk/helper/ocsp/client.go:119:6: type certID is unused (unused)
type certID struct {
sdk/helper/ocsp/client.go:134:5: var hashOIDs is unused (unused)
var hashOIDs = map[crypto.Hash]asn1.ObjectIdentifier{
sdk/helper/ocsp/client.go:142:6: func getOIDFromHashAlgorithm is unused (unused)
func getOIDFromHashAlgorithm(target crypto.Hash) (asn1.ObjectIdentifier, error) {
sdk/helper/ocsp/client.go:155:18: func (*Client).getHashAlgorithmFromOID is unused (unused)
func (c *Client) getHashAlgorithmFromOID(target pkix.AlgorithmIdentifier) crypto.Hash {
sdk/helper/ocsp/client.go:190:18: func (*Client).encodeCertIDKey is unused (unused)
func (c *Client) encodeCertIDKey(certIDKeyBase64 string) (*certIDKey, error) {
sdk/helper/ocsp/client.go:751:18: func (*Client).extractOCSPCacheResponseValueWithoutSubject is unused (unused)
func (c *Client) extractOCSPCacheResponseValueWithoutSubject(cacheValue ocspCachedResponse) (*ocspStatus, error) {
sdk/helper/ocsp/ocsp_test.go:596:7: const vaultCert is unused (unused)
const vaultCert = `-----BEGIN CERTIFICATE-----
sdk/helper/stepwise/stepwise_test.go:20:5: var testTesting is unused (unused)
var testTesting = false
sdk/helper/testcluster/docker/environment.go:227:26: func (*DockerCluster).clusterReady is unused (unused)
func (dc *DockerCluster) clusterReady(ctx context.Context) error {
sdk/helper/testcluster/exec.go:33:2: field clientAuthRequired is unused (unused)
	clientAuthRequired bool
sdk/logical/request.go:190:2: field lastRemoteWAL is unused (unused)
	lastRemoteWAL uint64
api/client_test.go:551:7: type fields is unused (unused)
	type fields struct{}
api/sys_policy.go:131:6: type getPoliciesResp is unused (unused)
type getPoliciesResp struct {
api/sys_policy.go:135:6: type listPoliciesResp is unused (unused)
type listPoliciesResp struct {
```

### PR DESCRIPTION
**Pull request by phyrog**
Resolves #1575 

This deletes all the unused code found by golangci-lint (or in some cases adds `//nolint:unused` with additional explanation why it is unused).

### CODE REVIEW

File: vault/namespace_store.go [hunk 1]
```diff
@@ -263,17 +263,6 @@ func (c *Core) teardownNamespaceStore() error {
...
-func (ns *NamespaceStore) invalidate(ctx context.Context, path string) error {
-	// We want to keep invalidation proper fast (as it holds up replication),
-	// so defer invalidation to the next load.
-	//
-	// TODO(ascheel): handle individual entry invalidation correctly. We'll
-	// need to handle child namespace invalidation as well. sync.Map could be
-	// used instead in the future alongside the actual boolean.
-	ns.invalidated.Store(true)
-	return nil
-}
```
Comment (wslabosz-reply) [inline vault/namespace_store.go]: this one is definitely being used in the `HandleRequestsByStandbyNodes` effort, would probably leave it? (also the comment explains why it's not implemented yet)

Comment (phyrog) [reply vault/namespace_store.go]: Wasn't aware that code from that effort were already in main. I'll add a nolint comment for this and PolicyStore.invalidate

Comment (wslabosz-reply) [reply vault/namespace_store.go]: It's not yet on main, it's on the feature branch here https://github.com/openbao/openbao/compare/main...read-replication

Comment (phyrog) [reply vault/namespace_store.go]: Actually, I checked the history for these functions. This is already 7 months old and was part of the initial NamespaceStore setup. The method of PolicyStore is 7 years old. So it is not part of HandleRequestsByStandbyNodes.

Comment (wslabosz-reply) [reply vault/namespace_store.go]: didn't mean `HandleRequestsByStandbyNodes` as function (wasn't aware that it is a function overall), meant it as a horizontal scalability/read replication wg effort.

Comment (phyrog) [reply vault/namespace_store.go]: Ok I see they are used in the new code. I'll add the comments.

File: builtin/credential/jwt/path_cel_login.go [hunk 2]
```diff
@@ -211,26 +209,6 @@ func (b *jwtAuthBackend) runCelProgram(ctx context.Context, operation logical.Op
 	return nil, fmt.Errorf("Cel program '%s' returned unexpected type: %T", celRoleEntry.Name, result)
 }
 
-func (b *jwtAuthBackend) pathCelLoginRenew(ctx context.Context, req *logical.Request, data *framework.FieldData) (*logical.Response, error) {
```
Comment (phyrog) [inline builtin/credential/jwt/path_cel_login.go:214]: CEL is still a current topic, so not sure if this is planned for later usage or if this really is not needed anymore. @suprjinx I believe you added this code a couple of months ago.

Comment (cipherboy) [reply builtin/credential/jwt/path_cel_login.go:214]: Ahh, I see the problem.  I'll open a separate PR for this @wslabosz-reply @phyrog @suprjinx.

File: builtin/credential/cert/path_crls.go [hunk 3]
```diff
@@ -177,33 +176,6 @@ func (b *backend) findSerialInCRLs(serial *big.Int) map[string]RevokedSerialInfo
 	return ret
 }
 
-func parseSerialString(input string) (*big.Int, error) {
```
Comment (cipherboy) [inline builtin/credential/cert/path_crls.go:180]: Now I wonder what this was used for... :thinking:

File: builtin/credential/cert/path_login.go [hunk 4]
```diff
@@ -662,15 +662,6 @@ func (b *backend) checkForChainInCRLs(chain []*x509.Certificate) bool {
 	return badChain
 }
 
-func (b *backend) checkForValidChain(chains [][]*x509.Certificate) bool {
```
Comment (cipherboy) [inline builtin/credential/cert/path_login.go:665]: This looks fine as `matchesConstraints` calls `checkForChainInCRLs`.

File: builtin/credential/cert/path_crls.go (hunk 3 above)
Comment (cipherboy) [reply builtin/credential/cert/path_crls.go:180]: Ah, cert auth, not PKI. No matter. I think it is dead code after I fixed the earlier Cert Auth CVE likely.

File: builtin/credential/jwt/path_cel_login.go (hunk 2 above)
Comment (cipherboy) [reply builtin/credential/jwt/path_cel_login.go:214]: @phyrog I'd restore this, #1776 should keep this code path.

File: builtin/logical/kv/path_metadata.go [hunk 5]
```diff
@@ -812,11 +812,3 @@ func (b *versionedKVBackend) pathMetadataDelete() framework.OperationFunc {
 		return nil, err
 	}
 }
-
-const (
-	metadataHelpSyn  = `Allows interaction with key metadata and settings in the KV store.`
```
Comment (cipherboy) [inline builtin/logical/kv/path_metadata.go:820]: This seems like a bug; maybe the handlers above should be fixed:

```go
		HelpSynopsis:    confHelpSyn,
		HelpDescription: confHelpDesc,
```

is a bug.

File: builtin/logical/pki/crl_util.go [hunk 6]
```diff
@@ -506,35 +490,6 @@ func fetchIssuerMapForRevocationChecking(sc *storageContext) (map[issuerID]*x509
 	return issuerIDCertMap, nil
 }
 
-// Revoke a certificate from a given serial number if it is present in local
-// storage.
-func tryRevokeCertBySerial(sc *storageContext, config *crlConfig, serial string) (*logical.Response, error) {
```
Comment (cipherboy) [inline builtin/logical/pki/crl_util.go:511]: This is fine to remove, it only occurs in the context of cross-cluster revocation which I think we removed.

File: builtin/logical/pki/test_helpers.go [hunk 7]
```diff
@@ -393,20 +369,6 @@ func waitForUpdatedCrlUntil(t *testing.T, client *api.Client, crlPath string, la
 	}
 }
 
-// A quick CRL to string to provide better test error messages
-func summarizeCrl(t *testing.T, crl *x509.RevocationList) string {
```
Comment (cipherboy) [inline builtin/logical/pki/test_helpers.go:396]: This not being used is fine, though maybe we should.

File: builtin/logical/pki/test_helpers.go [hunk 8]
```diff
@@ -423,27 +385,3 @@ func requireOcspResponseSignedBy(t *testing.T, ocspResp *ocsp.Response, issuer *
 	err := ocspResp.CheckSignatureFrom(issuer)
 	require.NoError(t, err, "Failed signature verification of ocsp response: %w", err)
 }
-
-func performOcspPost(t *testing.T, cert *x509.Certificate, issuerCert *x509.Certificate, client *api.Client, ocspPath string) *ocsp.Response {
```
Comment (cipherboy) [inline builtin/logical/pki/test_helpers.go:426]: This not being used is more worrisome. We should probably keep it and use it.

File: helper/storagepacker/storagepacker.go [hunk 9]
```diff
@@ -22,7 +22,6 @@ import (
 )
 
 const (
-	bucketCount = 256
```
Comment (cipherboy) [inline helper/storagepacker/storagepacker.go:25]: This seems strange, tbh.

File: physical/raft/raft_test.go [hunk 10]
```diff
@@ -29,53 +29,6 @@ import (
 	"google.golang.org/protobuf/proto"
 )
 
-func connectPeers(nodes ...*RaftBackend) {
```
Comment (cipherboy) [inline physical/raft/raft_test.go:32]: I wonder if these will be used in our cluster tests in the future?

File: sdk/helper/ocsp/client.go [hunk 11]
```diff
@@ -115,53 +102,17 @@ const (
...
-		}
-	}
-	return nil, fmt.Errorf("no valid OID is found for the hash algorithm: %v", target)
-}
-
 func (c *Client) ClearCache() {
 	c.ocspResponseCache.Purge()
 }
 
-func (c *Client) getHashAlgorithmFromOID(target pkix.AlgorithmIdentifier) crypto.Hash {
```
Comment (cipherboy) [inline sdk/helper/ocsp/client.go:155]: Surprised this is unused, tbh.

File: vault/counters.go [hunk 12]
```diff
@@ -8,8 +8,6 @@ import (
 )
 
 const (
-	requestCounterDatePathFormat = "2006/01"
```
Comment (cipherboy) [inline vault/counters.go:11]: I think this was used for client counts, is there anything still remaining?

File: vault/wrapping_util.go [hunk 13]
```diff
@@ -1,14 +0,0 @@
...
-
-package vault
-
-import (
-	"context"
-
-	"github.com/openbao/openbao/sdk/v2/logical"
-)
-
-func forwardWrapRequest(context.Context, *Core, *logical.Request, *logical.Response, *logical.Auth) (*logical.Response, error) {
```
Comment (cipherboy) [inline vault/wrapping_util.go]: @phil9909 @fatima2003 This is what I was talking about adding a new GRPC interface for _logical_ request forwarding rather than just `http`-level request forwarding.

File: vault/login_mfa.go [hunk 14]
```diff
@@ -2965,45 +2948,3 @@ func (b *LoginMFABackend) putMFALoginEnforcementConfig(ctx context.Context, eCon
 		Value: marshaledEntry,
 	})
 }
-
-var mfaHelp = map[string][2]string{
```
Comment (cipherboy) [inline vault/login_mfa.go:2967]: As above about K/V, suspect it is just an oversight?

File: vault/counters.go (hunk 12 above)
Comment (phyrog) [reply vault/counters.go:11]: Nothing left related to client counts, I believe.

File: physical/raft/raft_test.go (hunk 10 above)
Comment (phyrog) [reply physical/raft/raft_test.go:32]: IMO they are not so complicated that we could not recreate them when needed.

File: helper/storagepacker/storagepacker.go (hunk 9 above)
Comment (phyrog) [reply helper/storagepacker/storagepacker.go:25]: Strange that this is unused, or that it was there to begin with?

Comment (cipherboy) [reply helper/storagepacker/storagepacker.go:25]: Strange that it is unused.

File: builtin/logical/pki/test_helpers.go (hunk 8 above)
Comment (phyrog) [reply builtin/logical/pki/test_helpers.go:426]: The exact code from this function can be found in this test: https://github.com/openbao/openbao/blob/244ea3841d91822d25dab88999e7074f0a9760af/builtin/logical/pki/path_ocsp_test.go#L425-L440

So it is being used, just not in this function 🙂

File: builtin/logical/pki/test_helpers.go (hunk 7 above)
Comment (phyrog) [reply builtin/logical/pki/test_helpers.go:396]: I don't see much value in this. Since we are using testify for most of the CRL tests, the error messages are fine as they are, IMO.

File: sdk/helper/ocsp/client.go (hunk 11 above)
Comment (phyrog) [reply sdk/helper/ocsp/client.go:155]: This was unused in the commit that added this code 😄 https://github.com/openbao/openbao/commit/a61174815fa76c755838369fdcb39c7bfbc0fa09

File: vault/login_mfa.go (hunk 14 above)
Comment (phyrog) [reply vault/login_mfa.go:2967]: I think this is left over from the former `/sys/mfa/method/xyz` endpoints, that we don't have anymore (afaik).

File: vault/wrapping_util.go (hunk 13 above)
Comment (phyrog) [reply vault/wrapping_util.go]: So, do you want to keep this, or...?

Comment (cipherboy) [reply vault/wrapping_util.go]: @phyrog No, if we need it we'll create something different, feel free to drop.

File: vault/login_mfa.go (hunk 14 above)
Comment (cipherboy) [reply vault/login_mfa.go:2967]: Ah, gotcha. Thanks!

File: helper/storagepacker/storagepacker.go (hunk 9 above)
Comment (phyrog) [reply helper/storagepacker/storagepacker.go:25]: This was also already unused when it was added: https://github.com/openbao/openbao/commit/6b9ce0c8c50fb52fbcc59e6016276cf96fa146dc

File: builtin/logical/kv/path_metadata.go [hunk 15]
```diff
@@ -20,6 +20,17 @@ import (
 	"github.com/openbao/openbao/sdk/v2/logical"
 )
 
+const (
+	metadataHelpSyn  = `Allows interaction with key metadata and settings in the KV store.`
+	metadataHelpDesc = `
+This endpoint allows for reading, information about a key in the key-value
+store, writing key settings, and permanently deleting a key and all versions.
```
Comment (wslabosz-reply) [inline builtin/logical/kv/path_metadata.go]:
```suggestion
This endpoint allows for reading key metadata in the key-value
store, writing key settings, or permanently deleting a key and all its versions.
```

(but do not apply my suggestion as it, as you will have to edit the commits due to DCO)

File: builtin/logical/kv/path_metadata.go [hunk 16]
```diff
@@ -20,6 +20,17 @@ import (
...
+`
+	detailedMetadataHelpSyn  = `Allows listing detailed information about metadata keys in the KV store.`
```
Comment (wslabosz-reply) [inline builtin/logical/kv/path_metadata.go]:
```suggestion
	detailedMetadataHelpSyn  = `Allows listing detailed information about key metadata in the KV store.`
```

**Review by cipherboy — APPROVED** [review]
Thank you @phyrog!
