### PR TITLE
Make self-init failures fatal

### LINKED ISSUE #2190: Declarative Self-Init: Make failures fatal
**Describe the bug**

Running a self-init file with an obvious bug (e.g. `sys/policieZZZZZZZZZZZ/acl/magic`) results in a failure:

```
Beginning post-unseal configuration
...
initialize.[gitlab-auth (0)]: request.[manager-role (3)]: failed to evaluate request: 1 error occurred:
	* unsupported path
```

However, subsequent restart is OK:

```
2025-12-03T13:22:19.497-0600 [INFO]  core: usage gauge collection is disabled
2025-12-03T13:22:19.497-0600 [INFO]  core: post-unseal setup complete
```

This causes problems when executing under any auto-retry system (k8s, systemd, ...). If self-init fails, subsequent restart works.

We should probably have some self-init start/finished logic.

**To Reproduce**

1. Run `bao server ...` with bad config
2. Run `bao server ...` again without deleting data
3. See error

**Expected behavior**

OpenBao should fatally fail, forcing any task manager to enter into a retry-fail backoff loop. 

**Environment:**

`main`

OpenBao server configuration file(s):

```json
{
  "initialize":
  [
    {
      "gitlab-auth": {
        "request": [
          {
            "manager-policy": {
              "allow_failure": false,
              "data": {
                "policy": "path \"*\" { capabilities = [\"create\", \"read\", \"update\", \"delete\", \"list\", \"sudo\"] }"
              },
              "operation": "create",
              "path": "sys/policies/acl/secrets_manager"
            }
          }
        ]
      }
    }
  ]
}
```

**Additional context**

Discovered by @fcat

### PR DESCRIPTION
**Pull request by satoqz**
## Description

Cleaned up alternative for #2442 that plays well with Auto Seals being async and has an end to end test to actually validate this.

## Rationale

https://github.com/openbao/openbao/pull/2442#discussion_r3099356543

Resolves: #2190

## Acknowledgements

 - [x] By contributing this change, I certify I have not used generative AI
       (GitHub Copilot, Cursor, Claude Code, &c) in authoring these changes or
       filling out the pull request description or associated issue.
 - [x] By contributing this change, I certify I have signed-off on the
       [DCO ownership](https://developercertificate.org/) statement
       and this change did not use post-BUSL-licensed code from HashiCorp.
       Existing MPL-licensed code is still allowed, subject to attribution.
       Code authored by yourself and submitted to HashiCorp for inclusion is
       also allowed.

### CODE REVIEW

File: helper/profiles/profiles.go [hunk 1]
```diff
@@ -388,13 +388,15 @@ func (p *ProfileEngine) evaluateRequest(ctx context.Context, history *Evaluation
 	// 4. Call the request handler.
 	resp, err := p.requestHandler(ctx, req)
 	isFailure := err != nil || resp.IsError()
-	if err == nil && resp.IsError() {
+	if err == nil {
 		err = resp.Error()
 	}
```
Comment (satoqz) [inline helper/profiles/profiles.go:393]: `resp.Error()` already checks `resp.IsError()`. Neither do we need to check for `resp == nil`, which is already checked by `resp.IsError()`.

File: vault/external_tests/postgresql_binary/postgresql_test.go [hunk 2]
```diff
@@ -200,3 +202,58 @@ func TestPostgreSQL_ParallelInit(t *testing.T) {
...
+			// NewDockerCluster directly.
+			ClusterName: strings.ReplaceAll(t.Name(), "/", "-"),
+			Logger:      logging.NewVaultLogger(log.Trace).Named(t.Name()),
+		},
+	}
+
+	cluster, err := docker.NewDockerCluster(t.Context(), opts)
+
+	// Don't forget to clean up just in case the assertion below fails and the
+	// test cluster didn't fail as epxected.
```
Comment (wslabosz-reply) [inline vault/external_tests/postgresql_binary/postgresql_test.go]:
```suggestion
	// test cluster didn't fail as expected.
```

**Review by wslabosz-reply — APPROVED** [review]

File: vault/init.go [hunk 3]
```diff
@@ -484,7 +484,7 @@ func (c *Core) UnsealWithStoredKeys(ctx context.Context) error {
 
 	// Disallow auto-unsealing when migrating
 	if c.IsInSealMigrationMode(true) && !c.IsSealMigrated(true) {
-		return NewNonFatalError(errors.New("cannot auto-unseal during seal migration"))
+		return errors.New("cannot auto-unseal during seal migration")
```
Comment (cipherboy) [inline vault/init.go]: @satoqz Is this change mandatory or related to this PR? I think there's other cleanup that could be done if we are tweaking this now (`NewNonFatalError` is unused for instance, though `IsFatalError` is still used in a few places).

**Review by cipherboy — APPROVED** [review]

File: vault/init.go (hunk 3 above)
Comment (satoqz) [reply vault/init.go]: Not mandatory, I was looking at what the `IsFatalError` check in `runUnseal` actually did to see if I could hook into that, but then it turned out every single failure path returned a `NonFatalError` and there was no way to override this from deeper down the callstack, so I just removed it to lessen confusion.

Will remove from this patch.
