### PR TITLE
Remove usage of deprecated .Subjects() in test files

### LINKED ISSUE #575: tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.
**Describe the bug**
`tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.` is a warning in the following files: 

```
(base) fatimaopenbao % grep -r "Subjects()" .

./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./api/client_test.go:   if len(tlsConfig.RootCAs.Subjects()) == 0 {
./vault/diagnose/tls_verification.go:   rootSubjs := rootPool.Subjects()
```

**Expected behavior**
There should be no warning: 
```
tlsConfig.RootCAs.Subjects is deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.deprecated[default](https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/deprecated)
func (s *x509.CertPool) Subjects() [][]byte
Subjects returns a list of the DER-encoded subjects of all of the certificates in the pool.

Deprecated: if s was returned by [SystemCertPool], Subjects will not include the system roots.

```
___

This could be a quick fix, for instance in ./api/client_test.go, Simply replace `len(tlsConfig.RootCAs.Subjects()) == 0` With `tlsConfig.RootCAs == nil`             

I am looking for replacements in the other files. Should I open a PR after testing the changes?

### PR DESCRIPTION
**Pull request by fatima2003**
`tlsConfig.RootCAs.Subjects` deprecated and removed from test files.

```
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
./sdk/helper/certutil/certutil_test.go:                 if len(tlsConfig.RootCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.RootCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
```
In **certutil_test.go**, it was replaced by verifying if the leaf certs could be verified against the ClientCAs or RootCAs or both.

```
./api/client_test.go:   if len(tlsConfig.RootCAs.Subjects()) == 0 {
./vault/diagnose/tls_verification.go:   rootSubjs := rootPool.Subjects()
```
In these test files which were checking that the cert pools are not empty, I replaced them by checking the cert pool is not equal to an empty cert pool: `x509.NewCertPool().Equal(tlsConfig.RootCAs) `

Resolves #575 

## Target Release

1.14.7

### CODE REVIEW

File: sdk/helper/certutil/certutil_test.go [hunk 1]
```diff
@@ -411,25 +411,60 @@ func TestTLSConfig(t *testing.T) {
 
 		switch usage {
 		case TLSServer | TLSClient:
-			if len(tlsConfig.ClientCAs.Subjects()) != 1 || bytes.Compare(tlsConfig.ClientCAs.Subjects()[0], pcbut.CAChain[0].Certificate.RawSubject) != 0 {
-				t.Fatalf("CA certificate not in client cert pool as expected")
+			if tlsConfig.ClientCAs == nil {
```
Comment (cipherboy) [inline sdk/helper/certutil/certutil_test.go:414]: I think `ClientCAs` is just a copy of `RootCAs`, if present, but I'm happy to leave this as-is to validate it is indeed provisioned.

**Review by cipherboy — APPROVED** [review]
Looks great, thanks @fatima2003!
