### PR TITLE
Fix `/sys/remount` across namespaces

### LINKED ISSUE #1228: `/sys/remount` broken for namespaces
**Describe the bug**
Remounting a secret or auth backend in namespaces is not currently possible.

**To Reproduce**
```
bao namespace create ns1
bao namespace create ns2
bao secrets enable -ns ns1 kv
bao secrets move ns1/kv ns2/kv # error
bao secrets move -ns ns1 kv kv2 # error
```

**Expected behavior**
backends should be correctly remounted at the new location

**Additional context**

https://github.com/openbao/openbao/blob/5eecb4aee6bc69e80f48dc2b25d0e01d9eb2e66a/vault/mount.go#L1171 seems to not be namespace aware yet

### PR DESCRIPTION
**Pull request by phyrog**
Resolves #1228

### CODE REVIEW

File: vault/auth.go [hunk 1]
```diff
@@ -407,7 +407,7 @@ func (c *Core) remountCredential(ctx context.Context, src, dst namespace.MountPa
 	}
 
 	c.authLock.Lock()
-	if match := c.router.MountConflict(ctx, dstRelativePath); match != "" {
+	if match := c.router.MountConflict(ctx, dstRelativePath); match != dst.Namespace.Path {
 		c.authLock.Unlock()
 		return fmt.Errorf("path in use at %q", match)
 	}
```
Comment (cipherboy) [inline vault/auth.go:413]: Maybe I'm thinking about this wrong, but shouldn't storage migration happen while the route is tainted, so we don't get any new requests?

Line 415 executes before the router move in 431 that has been hooked, and so we risk new requests coming in while storage is being moved, which may result in weird happenstances when e.g., entries that should exist don't?

My 2c.

Comment (phyrog) [reply vault/auth.go:413]: I believe the `routeEntry` is still tainted at that point (old path tainted in 397, new path untainted in 524), so I think it should not be possible that new requests come in in the meantime. But I agree, it's weird that the `MountEntry` is untainted at that point. I'll try to find out why that might be.

File: vault/mount.go [hunk 2]
```diff
@@ -1167,7 +1167,93 @@ func (c *Core) remountSecretsEngine(ctx context.Context, src, dst namespace.Moun
...
+		}
+		for i := 0; i < len(keys); i++ {
+			key := keys[i]
+			if strings.HasSuffix(key, "/") {
+				nestedKeys, err := view.List(ctx, re.storagePrefix+key)
+				if err != nil {
+					return err
+				}
+				for i := range nestedKeys {
+					nestedKeys[i] = key + nestedKeys[i]
```
Comment (wslabosz-reply) [inline vault/mount.go:1209]: I'd consider changing the iterator variable name from `i` as it is the same as the outer loop

File: vault/auth_test.go [hunk 3]
```diff
@@ -832,6 +832,77 @@ func TestCore_RemountCredential_Cleanup(t *testing.T) {
 	}
 }
 
+func TestCore_RemountCredential_Namesoaces(t *testing.T) {
```
Comment (wslabosz-reply) [inline vault/auth_test.go:835]:
```suggestion
func TestCore_RemountCredential_Namespaces(t *testing.T) {
```

File: vault/logical_system.go [hunk 4]
```diff
@@ -1341,7 +1341,7 @@ func (b *SystemBackend) handleRemount(ctx context.Context, req *logical.Request,
 		return handleError(fmt.Errorf("no matching mount at %q", sanitizePath(fromPath)))
 	}
 
-	if match := b.Core.router.MountConflict(ctx, sanitizePath(toPath)); match != "" {
+	if match := b.Core.router.MountConflict(ctx, sanitizePath(toPath)); match != toPathDetails.Namespace.Path {
```
Comment (satoqz) [inline vault/logical_system.go:1344]:
```suggestion
	if match := b.Core.router.MountConflict(ctx, sanitizePath(toPath)); match != toPathDetails.Namespace.Path && match != "" {
```

Comment (voigt) [reply vault/logical_system.go:1344]: Good catch!

File: vault/auth.go [hunk 5]
```diff
@@ -428,7 +428,93 @@ func (c *Core) remountCredential(ctx context.Context, src, dst namespace.MountPa
 
 	// Remount the backend, setting the existing route entry
 	// against the new path
-	if err := c.router.Remount(ctx, srcRelativePath, dstRelativePath); err != nil {
+	if err := c.router.Remount(ctx, srcRelativePath, dstRelativePath, func(re *routeEntry) error {
```
Comment (satoqz) [inline vault/auth.go:431]: I'm a bit unhappy with this long and complex callback, even more so since it's duplicated down to 99% between `auth.go` and `mount.go`.

Can we share (at least parts of it) between mounts and auth mounts?

I'm also not happy how the callback performs two operations in one:

- Moving storage entries
- Updating the route entry

These are separate concerns IMO, moving storage entries should not concern itself with the router yet.

I don't believe we need `re.storagePrefix` to move storage entries -- that value is initially set based on `mountEntryView(...)` so why not get something like a `srcBarrierView` the same way we get `dstBarrierView` a bit earlier before the mount table is updated?

I might be missing something here that makes a "cleaner" approach unfeasible, just wondering.

Comment (voigt) [reply vault/auth.go:431]: These are good points. I also felt kind of uncomfortable with the complexity of the function. Will try to improve it.
In regards to timing Namespaces Beta I wonder: shall we merge, create beta and then refactor or should we only merge refactored code?

Comment (satoqz) [reply vault/auth.go:431]: I suppose we're still waiting on reviews on #1279, so that's the bigger blocker for the beta. I'd say give it a try, and if the merge pressure catches up before the refactor bears fruit we can do it later?

File: vault/namespaces_store.go [hunk 6]
```diff
@@ -458,6 +459,24 @@ func (ns *NamespaceStore) GetNamespaceByPath(ctx context.Context, path string) (
...
+func (ns *NamespaceStore) GetNamespaceByLongestPrefix(ctx context.Context, path string) (*namespace.Namespace, string) {
+	ctxNs, err := namespace.FromContext(ctx)
+	if err != nil {
+		ctxNs = namespace.RootNamespace
+	}
+
+	// e.g. needed for /sys/unseal, where the namespace store is not yet initialized
+	if ns == nil {
+		return ctxNs, path
+	}
```
[the remark this answers is not in the document]
Comment (phyrog) [reply vault/namespaces_store.go]: It was needed for one of the tests, where the core was sealed and unsealed. Probably should be solved by #1279.

File: vault/logical_system.go
Comment (satoqz) [inline vault/logical_system.go:1]: There's a rather unclear error message when you try to remount to a path that is just a namespace path, no namespace + mount path:

```
* invalid destination mount: path '' does not match cleaned path '.'
```

(try with `bao namespace create test`, `bao secrets move secret test`)

There should probably be a check if `toPathDetails.MountPath` is empty.

**Comment by satoqz** [comment]
Ah, maybe you can rebase on namespaces to declutter CI failures. Although I doubt it will reveal anything new.

File: vault/logical_system.go
Comment (voigt) [reply vault/logical_system.go:1]: Good catch. Will look into that one and see if its worth having a dedicated test.

File: vault/mount_test.go [hunk 7]
```diff
@@ -733,6 +733,69 @@ func TestCore_Remount_Protected(t *testing.T) {
...
+	testCoreAddSecretMountContext(ns2Ctx, t, c, token)
+
+	src := namespace.MountPathDetails{
+		Namespace: ns2,
+		MountPath: "secret/",
+	}
+	dst := namespace.MountPathDetails{
+		Namespace: ns3,
+		MountPath: "secret2/",
+	}
```
[the remark this answers is not in the document]
Comment (voigt) [reply vault/mount_test.go:755]: Agree, that should be an easy one.

File: vault/mount.go [hunk 8]
```diff
@@ -1181,17 +1206,121 @@ func (c *Core) remountSecretsEngine(ctx context.Context, src, dst namespace.Moun
...
+	rollback := func(context.Context) error { return nil }
+	commit := func(context.Context) error { return nil }
+	if txnBarrier, ok := barrier.(logical.TransactionalStorage); ok {
+		tx, err := txnBarrier.BeginTx(ctx)
+		if err != nil {
+			return err
+		}
+		rollback = tx.Rollback
+		commit = tx.Commit
+		view = tx
```
Comment (cipherboy) [inline vault/mount.go:1236]: I don't think this works. In particular, if you run:

```
$ <start a Raft-based OpenBao>
$ ./dist/linux/amd64/benchmark-openbao run -log_level=trace -config=docs/examples/kv/kvv2-write.hcl 
2025-05-12T07:12:38.814-0500 [INFO]  vault-benchmark: setting up targets
2025-05-12T07:12:38.814-0500 [DEBUG] vault-benchmark: setting up target: target=kvv2_write_test
2025-05-12T07:12:38.814-0500 [TRACE] vault-benchmark.kvv2_write: mounting kvv2 secrets engine at: path=95c7b6c4-83d3-6c53-ea07-3955f9423870
2025-05-12T07:12:38.848-0500 [TRACE] vault-benchmark.kvv2_write.95c7b6c4-83d3-6c53-ea07-3955f9423870: seeding secrets
2025-05-12T07:12:44.467-0500 [INFO]  vault-benchmark: starting benchmarks: duration=10s
2025-05-12T07:12:54.505-0500 [INFO]  vault-benchmark: benchmark complete
Target: http://127.0.0.1:8200
op               count  rate        throughput  mean         95th%        99th%        successRatio
kvv2_write_test  3057   305.651387  304.541418  32.779336ms  52.952553ms  60.566257ms  100.00%
$ bao secrets move 95c7b6c4-83d3-6c53-ea07-3955f9423870/ testing/moved
Started moving secrets engine 95c7b6c4-83d3-6c53-ea07-3955f9423870/ to testing/moved/, with migration ID 13ada522-79a9-86c2-c84b-afe7b5d96aab
Waiting for terminal status in migration of secrets engine 95c7b6c4-83d3-6c53-ea07-3955f9423870/ to testing/moved/, with migration ID 13ada522-79a9-86c2-c84b-afe7b5d96aab
Failure! Error encountered moving secrets engine 95c7b6c4-83d3-6c53-ea07-3955f9423870/ to testing/moved/, with migration ID 13ada522-79a9-86c2-c84b-afe7b5d96aab
```

We see it fails with message:

```
2025-05-12T07:13:32.459-0500 [ERROR] core.mounts.migration: remount failed: from_path=95c7b6c4-83d3-6c53-ea07-3955f9423870/ migration_id=13ada522-79a9-86c2-c84b-afe7b5d96aab namespace="" to_path=testing/moved/ error="put failed due to value being too large; got 35756872 bytes, max: 8388608 bytes, 22802 operations in transaction"
```

because we exceeded the size of a Raft transaction.

If you are going to put a transaction around anything, I'd do a list and for each item, start a fresh transaction to do the actual move. This ensures atomicity of any given move and we can retry the operation as a whole, if needed.

A final list can be done in a transaction, any trailing contents moved, and then committed as well to ensure nothing gets created afterwards (if we were really paranoid that locking wasn't sufficient, though it should 100% be).

**Review by cipherboy — COMMENTED** [review]
I'd suggest the following change:


```diff
diff --git a/vault/mount.go b/vault/mount.go
index 5584c59af6..f46ad92d5c 100644
--- a/vault/mount.go
+++ b/vault/mount.go
@@ -1223,24 +1223,17 @@ func (c *Core) moveStorage(ctx context.Context, src namespace.MountPathDetails,
        dstPrefix := dstBarrierView.Prefix()
 
        barrier := c.barrier
-       var view logical.Storage = barrier
 
-       s := barrier.(logical.TransactionalStorage)
-
-       keys, err := s.List(ctx, srcPrefix)
+       var key string
+       keys, err := barrier.List(ctx, srcPrefix)
        if err != nil {
                return err
        }
 
-       for i := 0; i < len(keys); i++ {
-               tx, err := s.BeginTx(ctx)
-               if err != nil {
-                       err := tx.Rollback(ctx)
-                       return err
-               }
-               key := keys[i]
+       for len(keys) > 0 {
+               key, keys = keys[0], keys[1:]
                if strings.HasSuffix(key, "/") {
-                       nestedKeys, err := view.List(ctx, srcPrefix+key)
+                       nestedKeys, err := barrier.List(ctx, srcPrefix+key)
                        if err != nil {
                                return err
                        }
@@ -1252,28 +1245,27 @@ func (c *Core) moveStorage(ctx context.Context, src namespace.MountPathDetails,
                        continue
                }
 
-               se, err := view.Get(ctx, srcPrefix+key)
-               if err != nil {
-                       rErr := tx.Rollback(ctx)
-                       return errors.Join(err, rErr)
-               }
-               if se == nil {
-                       continue
-               }
+               if err := logical.WithTransaction(ctx, barrier, func(s logical.Storage) error {
+                       se, err := s.Get(ctx, srcPrefix+key)
+                       if err != nil {
+                               return err
+                       }
+                       if se == nil {
+                               return nil
+                       }
 
-               se.Key = dstPrefix + key
-               err = view.Put(ctx, se)
-               if err != nil {
-                       rErr := tx.Rollback(ctx)
-                       return errors.Join(err, rErr)
-               }
-               err = view.Delete(ctx, srcPrefix+key)
-               if err != nil {
-                       rErr := tx.Rollback(ctx)
-                       return errors.Join(err, rErr)
-               }
-               err = tx.Commit(ctx)
-               if err != nil {
+                       se.Key = dstPrefix + key
+                       err = s.Put(ctx, se)
+                       if err != nil {
+                               return err
+                       }
+
+                       err = s.Delete(ctx, srcPrefix+key)
+                       if err != nil {
+                               return err
+                       }
+                       return nil
+               }); err != nil {
                        return err
                }
        }
```

---

This doesn't trigger an actual deadlock, but because the mount move takes so long with 300MB of data (in the 9999 entries of 99kb mode we discussed on Matrix), we get deadlock warnings:

```
2025-05-13T10:52:25.075-0500 [INFO]  storage.raft: compacting logs: from=1 to=2628
2025-05-13T10:52:25.077-0500 [INFO]  storage.raft: snapshot complete up to: index=12868
2025-05-13T11:34:12.282-0500 [INFO]  core.mounts.migration: Starting to update the mount table and revoke leases: from_path=e4a716fb-d77a-765f-a962-4f7ee0c39967/ migration_id=50599b44-f5a0-6cbd-4e16-6b057cf0870c namespace="" to_path=testing/moved/
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 35292 lock 0xc0007228b0
~/GitHub/cipherboy/openbao/vault/mount.go:1154 vault.(*Core).remountSecretsEngine { c.mountsLock.Lock() } <<<<<
~/GitHub/cipherboy/openbao/vault/mount.go:1153 vault.(*Core).remountSecretsEngine {  }
~/GitHub/cipherboy/openbao/vault/logical_system.go:1393 vault.(*SystemBackend).moveMount { case mountTableType: }
~/GitHub/cipherboy/openbao/vault/logical_system.go:1363 vault.(*SystemBackend).handleRemount.func1 { err := b.moveMount(ns, logger, migrationID, entry, fromPathDetails, toPathDetails) }

Have been trying to lock it again for more than 30s
goroutine 542 lock 0xc0007228b0
~/GitHub/cipherboy/openbao/vault/rollback.go:360 vault.(*Core).startRollback.func1 { c.mountsLock.RLock() } <<<<<
~/GitHub/cipherboy/openbao/vault/rollback.go:359 vault.(*Core).startRollback.func1 { ret := []*MountEntry{} }
~/GitHub/cipherboy/openbao/vault/rollback.go:171 vault.(*RollbackManager).triggerRollbacks { func (m *RollbackManager) triggerRollbacks() { }
~/GitHub/cipherboy/openbao/vault/rollback.go:152 vault.(*RollbackManager).run { select { }

Here is what goroutine 35292 doing now
goroutine 35292 [runnable]:
time.Now()
	/home/cipherboy/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.2.linux-amd64/src/time/time.go:1340 +0x93
github.com/armon/go-metrics.(*AggregateSample).Ingest(0xc0020cdc20, 0xc002274c30?, 0xc000f86b20?)
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/inmem.go:118 +0x7a
github.com/armon/go-metrics.(*InmemSink).AddSampleWithLabels(0xc0007c4cd0, {0xc002000540?, 0x386e460?, 0x1?}, 0x432c0000, {0x0, 0x0, 0x0})
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/inmem.go:230 +0x29a
github.com/armon/go-metrics.FanoutSink.AddSampleWithLabels(...)
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/sink.go:82
github.com/armon/go-metrics.(*Metrics).AddSampleWithLabels(0xc000862000, {0xc0015b80c0, 0x2, 0x2a7820a?}, 0x432c0000, {0x0?, 0x419e45?, 0x20?})
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/metrics.go:106 +0x3d0
github.com/armon/go-metrics.(*Metrics).AddSample(...)
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/metrics.go:85
github.com/armon/go-metrics.AddSample({0xc0015b80c0?, 0xc000f92770?, 0xc000f57638?}, 0x0?)
	/home/cipherboy/go/pkg/mod/github.com/armon/go-metrics@v0.4.1/start.go:121 +0x7d
github.com/openbao/openbao/physical/raft.(*RaftBackend).applyLog(0xc000b80840, {0x4bcf170?, 0xc001853620?}, 0xc001e59bc0)
	/home/cipherboy/GitHub/cipherboy/openbao/physical/raft/raft.go:1818 +0x604
github.com/openbao/openbao/physical/raft.(*RaftBackend).Delete(0xc000b80840, {0x4bcf170, 0xc001853620}, {0xc00187bad0, 0xa4})
	/home/cipherboy/GitHub/cipherboy/openbao/physical/raft/raft.go:1618 +0x1e7
github.com/openbao/openbao/sdk/v2/physical.(*cache).Delete(0xc000381a40, {0x4bcf170, 0xc001853620}, {0xc00187bad0, 0xa4})
	/home/cipherboy/GitHub/cipherboy/openbao/sdk/physical/cache.go:262 +0x191
github.com/openbao/openbao/sdk/v2/physical.(*storageEncoding).Delete(0xc000503b40, {0x4bcf170, 0xc001853620}, {0xc00187bad0, 0xa4})
	/home/cipherboy/GitHub/cipherboy/openbao/sdk/physical/encoding.go:98 +0xfb
github.com/openbao/openbao/vault.(*AESGCMBarrier).deleteWithBackend(0xc000a18980, {0x4bcf170, 0xc001853620}, {0x4bd4d60, 0xc000503b40}, {0xc00187bad0, 0xa4})
	/home/cipherboy/GitHub/cipherboy/openbao/vault/barrier_aes_gcm.go:903 +0x151
github.com/openbao/openbao/vault.(*AESGCMBarrier).Delete(...)
	/home/cipherboy/GitHub/cipherboy/openbao/vault/barrier_aes_gcm.go:891
github.com/openbao/openbao/vault.(*Core).moveStorage.func1({0x7f47ff629598, 0xc0005ae698})
	/home/cipherboy/GitHub/cipherboy/openbao/vault/mount.go:1263 +0x154
github.com/openbao/openbao/sdk/v2/logical.WithTransaction({0x4bcf170, 0xc001853620}, {0x7f47ff629598?, 0xc0005ae698}, 0xc000f57bd0)
	/home/cipherboy/GitHub/cipherboy/openbao/sdk/logical/logical_storage.go:111 +0x147
github.com/openbao/openbao/vault.(*Core).moveStorage(0xc000722708, {0x4bcf170, 0xc001853620}, {0x7101920?, {0xc0018ef5f0?, 0xc000fdf1d0?}}, 0xc00062bc20, {0x4be5e40?, 0xc00185a140?}, {0x4be5e40, ...})
	/home/cipherboy/GitHub/cipherboy/openbao/vault/mount.go:1248 +0x627
github.com/openbao/openbao/vault.(*Core).moveMountStorage(...)
	/home/cipherboy/GitHub/cipherboy/openbao/vault/mount.go:1211
github.com/openbao/openbao/vault.(*Core).remountSecretsEngine(0xc000722708, {0x4bcf170, 0xc001853620}, {0x7101920, {0xc0018ef5f0, 0x25}}, {0xc000d06140, {0xc001187cb8, 0x6}}, 0x1)
	/home/cipherboy/GitHub/cipherboy/openbao/vault/mount.go:1183 +0xbea
github.com/openbao/openbao/vault.(*SystemBackend).moveMount(0xc000daf950, 0x7101920, {0x4bfc2c8, 0xc0018535f0}, {0xc0018efaa0, 0x24}, 0xc00062bc20, {0x7101920, {0xc0018ef5f0, 0x25}}, ...)
	/home/cipherboy/GitHub/cipherboy/openbao/vault/logical_system.go:1394 +0x199
github.com/openbao/openbao/vault.(*SystemBackend).handleRemount.func1({0xc0018efaa0, 0x24})
	/home/cipherboy/GitHub/cipherboy/openbao/vault/logical_system.go:1363 +0x3a5
created by github.com/openbao/openbao/vault.(*SystemBackend).handleRemount in goroutine 35303
	/home/cipherboy/GitHub/cipherboy/openbao/vault/logical_system.go:1357 +0xc45

2025-05-13T11:35:54.649-0500 [INFO]  storage.raft: starting snapshot up to: index=30954
2025-05-13T11:35:54.651-0500 [INFO]  storage.raft: compacting logs: from=2629 to=20715
2025-05-13T11:35:54.668-0500 [INFO]  storage.raft: snapshot complete up to: index=30954
2025-05-13T11:38:43.317-0500 [INFO]  core.mounts.migration: Updating quotas associated with the source mount: from_path=e4a716fb-d77a-765f-a962-4f7ee0c39967/ migration_id=50599b44-f5a0-6cbd-4e16-6b057cf0870c namespace="" to_path=testing/moved/
2025-05-13T11:38:43.317-0500 [INFO]  core.mounts.migration: Completed mount move operations: from_path=e4a716fb-d77a-765f-a962-4f7ee0c39967/ migration_id=50599b44-f5a0-6cbd-4e16-6b057cf0870c namespace="" to_path=testing/moved/
2025-05-13T11:39:14.171-0500 [INFO]  storage.raft: starting snapshot up to: index=58419
2025-05-13T11:39:14.174-0500 [INFO]  storage.raft: compacting logs: from=20716 to=48179
2025-05-13T11:39:14.187-0500 [INFO]  storage.raft: snapshot complete up to: index=58419
```

In the future, we can move it to something like `MoveView` and codify this pattern like in one of my draft PRs, but the approach above is fine for now.

**Review by satoqz — APPROVED** [review]

**Review by cipherboy — APPROVED** [review]
Thank you!
