### PR TITLE
Fix some staticcheck findings (nil pointer deref)

### LINKED ISSUE #1580: staticcheck (anything flagged by staticcheck; general code improvements, simplifications, ...) - 406 findings
Findings:

```
```

### PR DESCRIPTION
**Pull request by Huy-Dinh-Reply**
## Description

Fix false positive nil pointer dereference staticcheck findings by migrating some tests to testify.
Fix staticcheck warning about `t.Fatalf` being called in a sub goroutine

## Rationale

Resolves: #1580

## Acknowledgements

 - [x] By contributing this change, I certify I have not used generative AI
       (GitHub Copilot, Cursor, Claude Code, &c) in authoring these changes.
 - [x] By contributing this change, I certify I have signed-off on the
       [DCO ownership](https://developercertificate.org/) statement
       and this change did not use post-BUSL-licensed code from HashiCorp.
       Existing MPL-licensed code is still allowed, subject to attribution.
       Code authored by yourself and submitted to HashiCorp for inclusion is
       also allowed.

### CODE REVIEW

File: builtin/logical/database/backend_test.go [hunk 1]
```diff
@@ -91,13 +88,9 @@ func TestBackend_config_connection(t *testing.T) {
...
 	lb, err := Factory(context.Background(), config)
-	if err != nil {
-		t.Fatal(err)
-	}
+	require.NoError(t, err)
 	b, ok := lb.(*databaseBackend)
-	if !ok {
-		t.Fatal("could not convert to database backend")
-	}
+	require.Truef(t, ok, "could not convert to database backend")
```
Comment (wslabosz-reply) [inline builtin/logical/database/backend_test.go:93]: just an overall note, for `require.XXXf()` if you don't use any formatting, then it's alright to just use the command without `f` and the last arg is also a message (in this case ```require.True(t, ok, "could not convert to database backend")```
does the same thing)

**Review by wslabosz-reply — APPROVED** [review]

File: builtin/logical/database/backend_test.go (hunk 1 above)
Comment (Huy-Dinh-Reply) [reply builtin/logical/database/backend_test.go:93]: Thanks, will change this if there's something else we need to change as well.

File: command/agentproxyshared/cache/cache_test.go [hunk 2]
```diff
@@ -219,32 +219,30 @@ func TestCache_ConcurrentRequests(t *testing.T) {
...
-				t.Logf("failed to read value for key: %q", key)
-				t.Fail()
+				return fmt.Errorf("failed to read value for key: %q", key)
 			}
-		}(i)
+			return nil
+		})
+	}
 
+	if err := eg.Wait(); err != nil {
```
Comment (cipherboy) [inline command/agentproxyshared/cache/cache_test.go:243]: What is this sorcery? 😆 Love it!

**Review by cipherboy — APPROVED** [review]
I spot checked the test changes and nothing stood out to me, thanks @Huy-Dinh-Reply!

**Comment by cipherboy** [comment]
@Huy-Dinh-Reply Ah, but now we have conflicts. :laughing:

**Comment by Huy-Dinh-Reply** [comment]
@cipherboy @wslabosz-reply I rebased to fix the conflicts, some tests seem to be failing. On first look the tests seem unrelated to the change, maybe they are failing on main? 🤔

**Comment by wslabosz-reply** [comment]
AFAIK, yes these are unrelated.

**Comment by phyrog** [comment]
I re-ran the failed tests, seems to be flaky, they pass now.
