### PR TITLE
Fix unix-listener in `bao operator diagnose`

### LINKED ISSUE #957: `bao operator diagnose` incorrectly checks unix/socket listener for TLS, reports "failure"
with this bao config
```
api_addr = "https://openbao.example.com:10010"
pid_file = "/run/openbao/openbao.pid"

ui = false
disable_cache = true

log_file = "/var/log/openbao/openbao.log"
log_level = "trace"

storage "file" {
  path = "/data/db/openbao"
}

listener "unix" {
  address = "/run/openbao/openbao.sock"
  socket_mode  = "644"
  socket_user  = "openbao"
  socket_group = "openbao"
}

listener "tcp" {
  address       = "openbao.example.com:10010"
  tls_disable   = false
  tls_disable_client_certs = false
  tls_require_and_verify_client_cert = true
  tls_min_version = "tls13"
  tls_client_ca_file = "/usr/local/etc/openbao/myCA.crt.pem"
  tls_cert_file      = "/usr/local/etc/openbao/openbao.example.com.server.EC.crt.pem"
  tls_key_file       = "/usr/local/etc/openbao/openbao.example.com.server.EC.key.pem"
}
```

exec of `operator diagnose` reports "failure" incorrectly checking TLS for the "unix" socket listener -- which does not use TLS,
```
bao operator diagnose -config /usr/local/etc/openbao/openbao.hcl
	OpenBao v2.1.0+r3:git_main-0.20250128_224102.pgnd.fc41 (2c836911ee98abb1bb928e5457e141181d8161ac), built 2025-01-28T22:41:02Z

	Results:
	[ failure ] Vault Diagnose
	  [ success ] Check Operating System
	    [ success ] Check Open File Limits: Open file limits are set to 65535.
	    [ success ] Check Disk Usage: / usage ok.
	    ...
	  [ success ] Parse Configuration
	  [ warning ] Check Telemetry: Telemetry is using default configuration
	    By default only Prometheus and JSON metrics are available.  Ignore this warning if you are using
	    telemetry or are using these metrics and are satisfied with the default retention time and gauge period.
	  [ success ] Check Storage
	    [ success ] Create Storage Backend
	    [ success ] Check Storage Access
	  [ skipped ] Check Service Discovery: No service registration configured.
	  [ success ] Create Vault Server Configuration Seals
	  [ skipped ] Check Transit Seal TLS: No transit seal found in seal configuration.
	  [ success ] Create Core Configuration
	    [ success ] Initialize Randomness for Core
	  [ success ] HA Storage
	    [ success ] Create HA Storage Backend
	    [ skipped ] Check HA Consul Direct Storage Access: No HA storage stanza is configured.
	  [ success ] Determine Redirect Address
	  [ success ] Check Cluster Address: Cluster address is logically valid and can be found.
	  [ success ] Check Core Creation
	  [ failure ] Start Listeners
??	    [ failure ] Check Listener TLS: /run/openbao/openbao.sock: Failed to read certificate file: open
	      : no such file or directory.
	    [ failure ] Create Listeners: Error initializing listener of type tcp: listen tcp
	      127.0.0.1:10010: bind: address already in use
	  [ skipped ] Check Autounseal Encryption: Skipping barrier encryption test. Only supported for
	    auto-unseal.
	  [ success ] Check Server Before Runtime
	  [ success ] Finalize Shamir Seal
```

checking `./vault/diagnose/tls_verification.go`, there appears to be no exclusion for unix/socket listeners.

### PR DESCRIPTION
**Pull request by ajaygk95**
Resolves #957

`bao operator diagnose` skips listener TLS checks for unix-socket based listeners

### CODE REVIEW

**Comment by ajaygk95** [comment]
TODO: Add Changelog

File: vault/diagnose/tls_verification.go [hunk 1]
```diff
@@ -38,6 +38,12 @@ func ListenerChecks(ctx context.Context, listeners []*configutil.Listener) ([]st
 	for _, l := range listeners {
 		listenerID := l.Address
 
+		l.Type = strings.ToLower(l.Type)
```
Comment (cipherboy) [inline vault/diagnose/tls_verification.go:41]: Listener is a pointer, so this mutates it for other callers, which isn't nice. Do you mind rolling this into the next line if it's a pattern used elsewhere? I'm not sure if this really is a case-insensitive field. 

Ty!

**Review by cipherboy — APPROVED** [review]
