### PR TITLE
Fix incorrect references of `-plugin-version` arg in the documentation

### LINKED ISSUE #1890: `bao plugin register` with `-version` results in: "flag provided but not defined: -plugin-version"
**Describe the bug**
The [documentation](https://openbao.org/docs/commands/plugin/register/#command-options) describes the option `-version`:

```text
-plugin-version (string: "") - Semantic version of the plugin to run from the catalog. If unspecified, refers to the unversioned plugin registered with the same name and type, or the built-in plugin, in that order of precedence.
```

But that option is not processed:

```bash
$ bao plugin register -sha256=some_sh256_sum -plugin-version 0.1.0 secret openbao-plugin-secrets-aws 
flag provided but not defined: -plugin-version
```

**To Reproduce**
1. Run `bao plugin register -sha256=some_sh256_sum -plugin-version 0.1.0 secret openbao-plugin-secrets-aws`
2. See error: `flag provided but not defined: -plugin-version`

**Expected behavior**
Either the documentation should not describe this option, or (better) bao should allow me to set a version for the plugin.

**Environment:**
* OpenBao Server Version (retrieve with `bao status`): 2.4.1 (and 2.4.0)
* OpenBao CLI Version (retrieve with `bao version`): 2.4.1 (and 2.4.0)
* Server Operating System/Architecture: Ubuntu 24.04

OpenBao server configuration file(s):

```hcl
ui = true


plugin_directory = "/opt/openbao/plugins"

storage "raft" {
  path = "/opt/openbao/raft"
  node_id = "openbao-1"
}

cluster_addr = "http://127.0.0.1:8201"

api_addr = "http://127.0.0.1:8200"

listener "tcp" {
  address = "0.0.0.0:8200"
  tls_disable = true
}
```

### PR DESCRIPTION
**Pull request by wslabosz-reply**
Resolves #1890

### CODE REVIEW

File: command/plugin_info.go [hunk 1]
```diff
@@ -39,6 +39,10 @@ Usage: bao plugin info [options] TYPE NAME
 
       $ bao plugin info database mysql-database-plugin
 
+  Get info about a specific version of plugin:
```
Comment (satoqz) [inline command/plugin_info.go]:
```suggestion
  Get info about a specific version of a plugin:
```

**Review by satoqz — APPROVED** [review]

**Review by JanMa — APPROVED** [review]
