### PR TITLE
Forbid illegal namespace characters

### LINKED ISSUE #1183: Namespace name fuzzing results
**Describe the bug**
Based on discussions in Matrix and during the Namespace WG call, I am running some fuzz tests on namespace names to discover which characters might be causing issues. These tests are end-to-end, doing actual HTTP requests, so the whole stack should be covered.

These are the results I have so far (will update once I discover more):

- [ ] `+*` (and any other broken wildcard):
  - ```
    1 error occurred:\n\t* failed to modify namespace: error creating default policies: failed to load default policy: error parsing default policy: failed to parse policy: path \"+*/auth/token/lookup-self\": invalid use of wildcards ('+*' is forbidden)\n\n
    ```
- [ ] ` ` (space)
  - The error message is correct, but should return `400` instead of `500`
  - ```
    "1 error occurred:\n\t* failed to modify namespace: failed validating namespace: \" Q\" contains space characters and cannot be used as a namespace name\n\n"
  ```

**Expected behavior**
For any `500` error that we encounter, we should decide if we want to fix the code to allow namespaces with the failing name, or decide to forbid this name/character and return the proper `400` status.

**Additional context**
`namespaces` branch

### PR DESCRIPTION
**Pull request by phyrog**
This adds a fuzz test for the namespaces API to check for characters that cause problems. It also adds checks to the `(*Namespace).Validate` function for the characters found so far. All illegal characters now return a `400` error code, except for:

- `.`, and `..` return `405` and `404` respectively. They are interpreted by the HTTP stack, so these never reach the actual namespace validation. Not much that we can do here, I'm afraid.

Resolves #1183 

cc: @cipherboy @driif @klaus-sap @satoqz @voigt @wslabosz-reply @genelet

### CODE REVIEW

File: helper/namespace/namespace.go [hunk 1]
```diff
@@ -52,11 +57,21 @@ func (n *Namespace) Validate() error {
...
 			return fmt.Errorf("namespace name cannot be empty")
 		}
-		if strings.Contains(segment, " ") {
-			return fmt.Errorf("%q contains space characters and cannot be used as a namespace name", segment)
-		}
-		if slices.Contains(reservedNames, segment) {
-			return fmt.Errorf("%q is a reserved path and cannot be used as a namespace name", segment)
+
+		for _, r := range segment {
+			if slices.Contains(reservedNames, segment) {
```
Comment (wslabosz-reply) [inline helper/namespace/namespace.go:62]: this if clause should be outside (before the loop)

File: helper/namespace/namespace.go [hunk 2]
```diff
@@ -52,11 +57,21 @@ func (n *Namespace) Validate() error {
...
+				return fmt.Errorf("%q is a reserved path and cannot be used as a namespace name", segment)
+			}
+			switch {
+			case !utf8.ValidRune(r):
+				return fmt.Errorf("%q contains invalid utf-8 characters that cannot be used in a namespace name: %q", segment, r)
+			case !unicode.IsGraphic(r):
+				return fmt.Errorf("%q contains unicode characters that cannot be used in a namespace name: %q", segment, r)
+			case unicode.IsSpace(r):
+				return fmt.Errorf("%q contains space characters and cannot be used as a namespace name", segment)
```
Comment (wslabosz-reply) [inline helper/namespace/namespace.go:71]:
```suggestion
				return fmt.Errorf("%q contains space characters and cannot be used in a namespace name", segment)
```

File: helper/namespace/namespace.go (hunk 1 above)
Comment (phyrog) [reply helper/namespace/namespace.go:62]: We're checking each namespace segment for the reserved names, so it should be correct like this?

Comment (phyrog) [reply helper/namespace/namespace.go]: You're right :)

File: helper/namespace/namespace.go [hunk 3]
```diff
@@ -52,12 +57,22 @@ func (n *Namespace) Validate() error {
...
+		for _, r := range segment {
+			switch {
+			case !utf8.ValidRune(r):
+				return fmt.Errorf("%q contains invalid utf-8 characters that cannot be used in a namespace name: %q", segment, r)
+			case !unicode.IsGraphic(r):
+				return fmt.Errorf("%q contains unicode characters that cannot be used in a namespace name: %q", segment, r)
+			case unicode.IsSpace(r):
+				return fmt.Errorf("%q contains space characters and cannot be used in a namespace name", segment)
+			case r == '+' || r == '*':
+				return fmt.Errorf("%q contains wildcard characters and cannot be used in a namespace name: %q", segment, r)
```
Comment (wslabosz-reply) [inline helper/namespace/namespace.go:73]: sorry v2 😅 
```suggestion
				return fmt.Errorf("%q contains wildcard characters that cannot be used in a namespace name: %q", segment, r)
```

**Comment by phyrog** [comment]
> I'm not sure about the impact of changes in sdk/logical (probably non-existent), but everything looks right to me, great job!

I did not find any direct usages of `codedError` outside of that file, and since it still fulfills the `HTTPCodedError` interface it should be fine (as far as I can tell).

File: sdk/logical/error.go [hunk 4]
```diff
@@ -63,20 +63,27 @@ type HTTPCodedError interface {
...
 	}
 }
 
 var _ HTTPCodedError = (*codedError)(nil)
 
 type codedError struct {
-	Status  int
-	Message string
+	Status int
+	Err    error
```
Comment (driif) [inline sdk/logical/error.go:82]: @phyrog What are your thoughts on using "Error" instead of "Message" in coded errors? In my opinion, this change brings no advantages because you don't need to wrap error but could return CodedError(status, err.Error()) without needing to wrap the error. Could you please explain?

Comment (phyrog) [reply sdk/logical/error.go:82]: The thought was to allow proper go error wrapping with this, so things like `errors.Unwrap`, `errors.Is`, `errors.As` can be used on this (although I realize I did not add the `Unwrap` implementation`). `error` itself might already be wrapped, so using the existing implementation and call `err.Error()`, you'll loose that error wrapping hierarchy.

Comment (driif) [reply sdk/logical/error.go:82]: @phyrog Thank you for explanation. Seems like logical errors are mainly used to return response with the status code and simple error message. I don't think you'll need to check error at this stage, but I might be mistaken. IMO, we're adding a feature that might not be utilized.

I suggest not including this changes in this PR. If we want to improve error handling and implement a more standerdized and better approach for returning response errors, we should create an issue for it.

Comment (phyrog) [reply sdk/logical/error.go:82]: @driif Fair, I'll remove it 👍

File: vault/logical_system_namespaces.go [hunk 5]
```diff
@@ -231,7 +231,7 @@ func (b *SystemBackend) handleNamespacesSet() framework.OperationFunc {
 		path := namespace.Canonicalize(data.Get("path").(string))
 
 		if len(path) > 0 && strings.Contains(path[:len(path)-1], "/") {
-			return nil, errors.New("path must not contain /")
+			return handleError(logical.CodedError(http.StatusBadRequest, "path must not contain /"))
```
Comment (cipherboy) [inline vault/logical_system_namespaces.go:234]:
```suggestion
			return return logical.ErrorResponse("path must not contain /"), logical.ErrInvalidRequest
```

I think should also work fwiw.

Comment (phyrog) [reply vault/logical_system_namespaces.go]: @cipherboy fixed

**Review by driif — APPROVED** [review]

**Review by cipherboy — APPROVED** [review]
Thanks @phyrog! Always appreciate fuzz testing.

**Comment by cipherboy** [comment]
Ah, @phyrog this conflicts now that I merged @driif's tests. Sorry!

**Comment by phyrog** [comment]
@cipherboy rebased

**Review by wslabosz-reply — APPROVED** [review]

**Comment by cipherboy** [comment]
Thanks @phyrog!
