### PR TITLE
move namespace uuid into namespace struct

### LINKED ISSUE #1166: Move UUID field from NamespaceEntry to Namespace
**Describe the bug**
We have many cases of requiring the namespace UUID to construct storage paths. Since the UUID is not part of the `Namespace` struct stored in context, this requires additional lookups of the `NamespaceEntry` from the namespace store. To simplify this and decouple otherwise unrelated code from the namespace store, we should move the UUID into the `Namespace` struct.

**Examples**
- https://github.com/openbao/openbao/blob/a3edd3119ed66b7ad309fed983ab664e7627789b/vault/mount.go#L1612
- https://github.com/openbao/openbao/blob/a3edd3119ed66b7ad309fed983ab664e7627789b/vault/mount.go#L2195
  - and places where this is transitively used
- https://github.com/openbao/openbao/blob/a3edd3119ed66b7ad309fed983ab664e7627789b/vault/policy_store.go#L371
- other examples e.g. in #1123 

**Expected behavior**
UUID is contained in the `Namespace` struct, so we can avoid unnecessary redundant lookups in the namespace store.

### PR DESCRIPTION
**Pull request by phyrog**
Resolves #1166.

- Moves UUID field from `NamespaceEntry` into `Namespace`
- Removes unnecessary fetches from NamespaceStore
- Use `(*Core).ListNamespaces` and `(*Core).NamespaceByID` where now possible
- Removes `NamespaceEntry` completely

cc: @cipherboy, @driif, @voigt, @wslabosz-reply

### CODE REVIEW

**Comment by cipherboy** [comment]
> Removes `NamespaceEntry` completely (do we want to keep this?)

I'm happy removing it.

File: helper/namespace/namespace.go [hunk 1]
```diff
@@ -64,14 +65,16 @@ func (n *Namespace) Validate() error {
 }
 
 const (
-	RootNamespaceID = "root"
+	RootNamespaceID   = "root"
+	RootNamespaceUUID = "00000000-0000-0000-0000-000000000000"
```
Comment (cipherboy) [inline helper/namespace/namespace.go:69]: FWIW, `RootNamespaceID` doesn't conform to ID requirements (Vault's were 5 characters base 62, we're at 6 ourselves anyways).

Comment (cipherboy) [reply helper/namespace/namespace.go:69]: Ah, sorry, the latter.

File: vault/mount.go [hunk 2]
```diff
@@ -1609,17 +1609,7 @@ func (c *Core) persistMounts(ctx context.Context, barrier logical.Storage, table
 					continue
 				}
 
-				ne, err := c.namespaceStore.GetNamespaceByAccessor(ctx, mtEntry.NamespaceID)
```
Comment (cipherboy) [inline vault/mount.go:1612]: This will be nice :-)

File: vault/auth.go [hunk 3]
```diff
@@ -564,7 +564,7 @@ func (c *Core) loadCredentials(ctx context.Context) error {
 
 // This function reads the transactional split auth (credential) table.
 func (c *Core) loadTransactionalCredentials(ctx context.Context, barrier logical.Storage) error {
-	allNamespaces, err := c.namespaceStore.ListAllNamespaceEntries(ctx, true)
+	allNamespaces, err := c.ListNamespaces(ctx)
```
[the remark this answers is not in the document]
Comment (phyrog) [reply vault/auth.go:567]: Are these safeguards needed to get this PR merged, or are we fine with doing this later?

**Review by wslabosz-reply — APPROVED** [review]

File: vault/auth.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (phyrog) [reply vault/auth.go:567]: @cipherboy Alright, then we'd be done here from my perspective and ready for review.

**Review by cipherboy — APPROVED** [review]
This looks slick, many thanks @phyrog!

File: helper/namespace/namespace.go (hunk 1 above)
Comment (cipherboy) [reply helper/namespace/namespace.go:69]: I left this as-is for now @phyrog but we can revisit this later if we want.
